// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nohrizhxwrsinsyyojju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vaHJpemh4d3JzaW5zeXlvamp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjI2NTIsImV4cCI6MjA2ODMzODY1Mn0.-d4gBOgg1xWq1KR3TBNQSOmkZvb0CAuxwEc51rVcSyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});